CREATE TABLE OWNERS (
	ID INT IDENTITY NOT NULL,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	ADDRESS VARCHAR(255),
	CITY VARCHAR(80),
	TELEPHONE VARCHAR(20),
	PRIMARY KEY (ID)
);
CREATE TABLE PETS (
	ID INT IDENTITY NOT NULL,
	NAME VARCHAR(30),
	BIRTH_DATE DATE,
	TYPE_ID INT NOT NULL,
	OWNER_ID INT NOT NULL,
	PRIMARY KEY (ID)
);
CREATE TABLE SPECIALTIES (
	ID INT IDENTITY NOT NULL,
	NAME VARCHAR(80),
	PRIMARY KEY (ID)
);
CREATE TABLE TYPES (
	ID INT IDENTITY NOT NULL,
	NAME VARCHAR(80),
	PRIMARY KEY (ID)
);
CREATE TABLE VETS (
	ID INT IDENTITY NOT NULL,
	FIRST_NAME VARCHAR(30),
	LAST_NAME VARCHAR(30),
	PRIMARY KEY (ID)
);
CREATE TABLE VET_SPECIALTIES (
	VET_ID INT NOT NULL,
	SPECIALTY_ID INT NOT NULL
);
CREATE TABLE VISITS (
	ID INT IDENTITY NOT NULL,
	PET_ID INT NOT NULL,
	VISIT_DATE DATE,
	DESCRIPTION VARCHAR(255),
	PRIMARY KEY (ID)
);

ALTER TABLE PETS
	ADD FOREIGN KEY (OWNER_ID)
	REFERENCES OWNERS (ID);

ALTER TABLE PETS
	ADD FOREIGN KEY (TYPE_ID)
	REFERENCES TYPES (ID);

ALTER TABLE VET_SPECIALTIES
	ADD FOREIGN KEY (SPECIALTY_ID)
	REFERENCES SPECIALTIES (ID);

ALTER TABLE VET_SPECIALTIES
	ADD FOREIGN KEY (VET_ID)
	REFERENCES VETS (ID);

ALTER TABLE VISITS
	ADD FOREIGN KEY (PET_ID)
	REFERENCES PETS (ID);
